services:
  db:
    image: mysql:8.0
    container_name: fbnotes_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fb_notes_db
      MYSQL_USER: fbuser
      MYSQL_PASSWORD: fbpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - fbnotes_network

  web:
    build: .
    container_name: fbnotes_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
    networks:
      - fbnotes_network

volumes:
  db_data:

networks:
  fbnotes_network:
    driver: bridge
