version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: fbnotes_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fbnotes_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    #networks:
      #- fbnotes_network

  django:
    build:
      context:  .
      dockerfile: Dockerfile
    container_name: fbnotes_django
    command: python manage.py runserver 0.0.0.0:8000
             #python manage.py makemigrations &&
             #python manage.py migrate &&
             #python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/app
    ports:
      - "8000:8000"

    #working_dir: /app

    depends_on:
      - db
    environment:
      DB_NAME: fbnotes_db
      DB_USER: fbuser
      DB_PASSWORD: fbpass
      DB_HOST: db
      DB_PORT: 3306
    networks:
      - fbnotes_network

volumes:
  mysql_data:

networks:
  fbnotes_network:
    driver: bridge
